### ISSUE TITLE
buf and win -api calls not working

### ISSUE THREAD

**Issue by svampkorg** [Isrothy/neominimap.nvim#148]
**Describe the bug**
When trying to call the win -api calls, I get a lua error that says :
Error executing lua callback: ...local/share/nvim/lazy/neominimap.nvim/lua/neominimap.lua:56: module 'neominimap.command.window' not found:

**To Reproduce**
Using require("neominimap").winOff({}, { win = win }) or winOff

**Expected behavior**
no error

**Please complete the following information:**
- OS: macOS
- Neovim Version: 0.10.1

I noticed the modules for neominimap/command/window and neominimap/command/buffer have been renamed to win and buf in this patch here:
![Screenshot 2024-08-24 at 11 21 43](https://github.com/user-attachments/assets/06d7f747-56c6-4c29-b17a-157f2d8287c8)
So I did some changes in the neominimap.lua file and this seem to help:
![Screenshot 2024-08-24 at 11 16 41](https://github.com/user-attachments/assets/45666d22-73bc-4927-8b8d-49e7ff387b06)

Have a nice weekend :^)

**Comment by Isrothy** [comment]
Thank you for pointing this out!
