### ISSUE TITLE
Current line - draw it on top of git  signs

### ISSUE THREAD

**Issue by JoseConseco** [Isrothy/neominimap.nvim#149]
**Is your feature request related to a problem? Please describe.**
I wish that current line highlight was 'more important' than git signs lines - meaning cursor highlight was rendered on top of 'git sign'  line highlight.  I think showing where I am in current document, is more important than showing git signs (maybe it is just me)
![image](https://github.com/user-attachments/assets/77e42783-7f51-4061-97ed-5d439f4e13d4)
In above image u can see that current line is invisible on minimap - it is covered by git chagnes.

**Describe the solution you'd like**
Render current line highlight on minimap with higher priority.

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by Isrothy** [comment]
Unfortunately, the background highlight of the current line is produced by the cursor line, not by extmarks. As a result, I can’t change its priority.
