### ISSUE TITLE
Todo Comments

### ISSUE THREAD

**Issue by spencer-thompson** [Isrothy/neominimap.nvim#156]
**Is your feature request related to a problem? Please describe.**
Perhaps some confusion relating to how the mini map finds highlights. I went down a rabbit hole trying to figure out why [statuscol.nvim](https://github.com/luukvbaal/statuscol.nvim) breaks all the handlers. This wasn't too big of a deal to me though.

**Describe the solution you'd like**
Looking at the other handler files it seems like it won't be too difficult to implement, but once I get some time I will probably open a pull request.

To put it more clearly, I would like to add a handler for [todo-comments.nvim](https://github.com/folke/todo-comments.nvim)

The highlight group names are as follows:

* `TodoSignTODO`
* `TodoSignWARN`
* `TodoSignFIX`
* `TodoSignPERF`
* `TodoSignNOTE`

I think there might be one or two more, see the link above if needed.

**Describe alternatives you've considered**
I haven't really thought of anything else. I do like this plugin though, and would love to contribute :)

**Additional context**
![image](https://github.com/user-attachments/assets/f5444437-1994-429a-905a-47eebfc99d59)

**Comment by spencer-thompson** [comment]
Disregard what I said about the statuscol.nvim plugin. I figured that part out.

**Comment by Isrothy** [comment]
Thank you for the suggestion! I’m not sure whether we need to directly integrate todo-comments.nvim or if it could be handled using regular expressions. I’m currently considering exposing a handler API that would allow users to register their own handlers. This way, the internal code wouldn’t need frequent updates for specific integrations. Would love to hear your thoughts on this approach.

**Comment by spencer-thompson** [comment]
I like that a lot. Another idea, or inspiration is [transparent.nvim](https://github.com/xiyaowong/transparent.nvim) where you give the plugin a string as a prefix and it handles the background highlights for all highlight groups with that prefix. I am sure this is itself just a regex but could possibly make it more easy to use for anyone that doesn't know regex.

Example: `require('transparent').clear_prefix('gitsigns')`

If you could pass that (or something like it) into the config that would be pretty slick.

**Comment by Isrothy** [comment]
I really like your idea! However, since it’s more of a hack, I won’t be implementing it directly into the plugin. Instead, I’ll expose it through the API, and it will be documented in the tips section of the wiki for those who want to use it. Just a heads-up, I’m heading back to school soon, so updates might be a bit slower.

**Comment by spencer-thompson** [comment]
No worries, good to know. I am excited to see. I'm at school too so I understand haha

**Comment by Isrothy** [comment]
Please checkout `v3.6.0` and the [wiki](https://github.com/Isrothy/neominimap.nvim/wiki/Custimized-Handlers)
