### ISSUE TITLE
bug: neominimap no longer follows config in lazy.vim 

### ISSUE THREAD

**Issue by Reverier-Xu** [Isrothy/neominimap.nvim#177]
### Did you read the documentation and check existing issues?

- [X] I have read all the [`:help plugin-template`](https://github.com/Isrothy/neominimap.nvim/blob/main/doc/neominimap.nvim.txt) documentation
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the [existing issues](https://github.com/Isrothy/neominimap.nvim/issues) and [closed issues](https://github.com/Isrothy/neominimap.nvim/issues?q=is%3Aissue+is%3Aclosed) issues

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Arch Linux

### Describe the bug

neominimap no longer read config from Lazy.vim's opts config after commit c6eb1d8 :

![image](https://github.com/user-attachments/assets/f2282520-26df-4358-b909-1a94e6583f91)

both the float window width and border configs are ignored.

checkout to 3.7.3 fixes this.

### Steps To Reproduce

1. install this plugin with lazy.vim
2. modify configs
3. start nvim

### Expected Behavior

the config should works like 3.7.3:

![image](https://github.com/user-attachments/assets/14da36b5-cf7a-429b-9e7d-28a60b0e520a)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
    {
        -- Add anything you need here (configuration, other plugins, etc)
        "Isrothy/neominimap.nvim",
    },
})
```

**Comment by Isrothy** [comment]
The plugin wasn’t meant to use `opts` in lazy.vim. To set up the plugin, you can do this:

```lua
init = function()
  --- Put your configuration here
  ---@type Neominimap.UserConfig
  vim.g.neominimap = {
    auto_enable = true,
  }
end,
```
