### ISSUE TITLE
neominimap cannot show minimap for the 1st buffer

### ISSUE THREAD

**Issue by delphinus** [Isrothy/neominimap.nvim#24]
I open a file at the first time, then neominimap does not show minimap for the file. When I open another file again, neominimap shows the one.

[![asciicast](https://asciinema.org/a/667877.svg)](https://asciinema.org/a/667877)

I've recorded with this minimal config below.

<details><summary>reproducible init.lua</summary>

```lua
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  { "nvim-treesitter/nvim-treesitter", build = ':TSInstall lua' },
  {
    "Isrothy/neominimap.nvim",
    init = function()
      vim.opt.wrap = false       -- Recommended
      vim.opt.sidescrolloff = 36 -- It's recommended to set a large value
      vim.g.neominimap = {
        auto_enable = true,
      }
    end,
  },
})
```
</details>

**Comment by Isrothy** [comment]
Has this commit solved the issue? [5863669](https://github.com/Isrothy/neominimap.nvim/commit/58636692a779e021f70c6e056b7b6d3bf2010765)

**Comment by Isrothy** [comment]
You may checkout branch [fix-issue-24](https://github.com/Isrothy/neominimap.nvim/tree/fix-issue-24)

**Comment by delphinus** [comment]
Great! I confirmed this is solved.
