### ISSUE TITLE
When Neovim launches with filenames, it ignores winhighlight.

### ISSUE THREAD

**Issue by delphinus** [Isrothy/neominimap.nvim#27]
When I launch Neovim with a command such as `nvim foo_bar.lua`, it ignores `NeominimapFoo` highlights in setup.

```lua
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  { "nvim-treesitter/nvim-treesitter", build = ':TSInstall lua' },
  {
    "Isrothy/neominimap.nvim",
    init = function()
      vim.opt.wrap = false       -- Recommended
      vim.opt.sidescrolloff = 36 -- It's recommended to set a large value
      vim.g.neominimap = {
        auto_enable = true,
      }
      vim.api.nvim_set_hl(0, "NeominimapCursorLine", { bg = "#ffffff" })
    end,
  },
})
```

1. `nvim foo_bar.lua` with settings above.
2. I expect this config makes CursorLine be white (`#ffffff`) color, but it does not.

<img width="537" alt="スクリーンショット 2024-07-14 0 30 38" src="https://github.com/user-attachments/assets/73c8214c-4347-4055-8426-863cc596e7dd">

**Comment by Isrothy** [comment]
Has [fd97608](https://github.com/Isrothy/neominimap.nvim/commit/fd9760841f0d5ae9cf1f489c25e7a2b23e968cdd) solved your issue?

**Comment by delphinus** [comment]
Yes, this is also solved. Thank you.
